steps:
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:teleport6.2-v0.1.0
    id: nonroot-setup
    args: ['chown', '-R', 'ci:ci', '/workspace']

  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-nonroot:teleport6.2-v0.1.0
    id: unit-test
    env:
      - TELEPORT_ETCD_TEST="yes"
    entrypoint: '/bin/bash'
    args: 
      - '-c'
      - 'rm -rf /usr/include/bcc; ln -s /workspace/build.assets/bcc /usr/include/bcc; (make run-etcd &); sleep 1; make test'
    timeout: 15m
timeout: 15m
options:
  machineType: 'E2_HIGHCPU_32'
  
